### ISSUE TITLE
Theme is not working anymore: Main.qml: Library import requires a version

### ISSUE THREAD

**Issue by GaetanLepage** [stepanzubkov/where-is-my-sddm-theme#32]
Hi,

The theme has stopped working for me.
Here is the log resulting from my trying the greeter in `test-mode`:
```
❮ sddm-greeter --test-mode --theme /run/current-system/sw/share/sddm/themes/where_is_my_sddm_theme/
High-DPI autoscaling Enabled
Reading from "/nix/store/w96iiqnpvs8qfs0prbqzvzi97bxx505d-desktops/share/wayland-sessions/sway.desktop"
Loading theme configuration from "/run/current-system/sw/share/sddm/themes/where_is_my_sddm_theme//theme.conf"
Socket error:  "QLocalSocket::connectToServer: Invalid name"
Loading file:///run/current-system/sw/share/sddm/themes/where_is_my_sddm_theme//Main.qml...
file:///run/current-system/sw/share/sddm/themes/where_is_my_sddm_theme//Main.qml: Library import requires a version
file:///run/current-system/sw/share/sddm/themes/where_is_my_sddm_theme//Main.qml: Library import requires a version
Fallback to embedded theme
file:///nix/store/c0d2m7313gsl4kbqjqvfryvqzmm4ji9q-sddm-unwrapped-0.21.0/lib/qt-5.15.12/qml/SddmComponents/LayoutBox.qml:35:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/theme/Main.qml:41:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Adding view for "DP-2" QRect(0,0 2560x1440)
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

As a comparison, here is the log for the `maya` built-in theme, which works fine:
```
❯ sddm-greeter --test-mode --theme /run/current-system/sw/share/sddm/themes/maya
High-DPI autoscaling Enabled
Reading from "/nix/store/w96iiqnpvs8qfs0prbqzvzi97bxx505d-desktops/share/wayland-sessions/sway.desktop"
Loading theme configuration from "/run/current-system/sw/share/sddm/themes/maya/theme.conf"
Socket error:  "QLocalSocket::connectToServer: Invalid name"
Loading file:///run/current-system/sw/share/sddm/themes/maya/Main.qml...
file:///nix/store/c0d2m7313gsl4kbqjqvfryvqzmm4ji9q-sddm-unwrapped-0.21.0/lib/qt-5.15.12/qml/SddmComponents/LayoutBox.qml:35:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///run/current-system/sw/share/sddm/themes/maya/Main.qml:75:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Adding view for "DP-2" QRect(0,0 2560x1440)
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

So the issue seems t be this `Library import requires a version` message that directly precedes the `Fallback to embedded theme` and is not present in the maya logs.

**Comment by stepanzubkov** [comment]
Try qt5 theme

**Comment by ElrohirGT** [comment]
Can confirm this happens with NixOS too! I'll try to pack the qt5 theme maybe that'll work...

**Comment by ElrohirGT** [comment]
The qt5 theme works! At least when I try to run it with:

```bash
sddm-greeter --test-mode --theme {path to my config dir}
```

The image appears blurred... This was not the case with the previous theme, do the configs change between the two?
![image](https://github.com/stepanzubkov/where-is-my-sddm-theme/assets/45268815/5ad147b5-f821-4433-a485-75805f27ad78)

**Comment by stepanzubkov** [comment]
Oh, I accidentally left `blurRadius=32` in the `theme.conf`. Setting `blutRadius=0` will solve your problem

**Comment by stepanzubkov** [comment]
Fixed in main branch

**Comment by GaetanLepage** [comment]
Thank you very much !

**Comment by GaetanLepage** [comment]
Actually, I still encounter the error using 1.9.2...

**Comment by stepanzubkov** [comment]
> Actually, I still encounter the error using 1.9.2...

Which error: error, described in topic or error with blurred background image? And which version of theme you are using now, qt5 or qt6?

**Comment by GaetanLepage** [comment]
Actually, I still encounter the error using 1.9.2...

> Which error: error, described in topic or error with blurred background image? And which version of theme you are using now, qt5 or qt6?

The error mentioned in the issue description.
I am using the qt6 version.

**Comment by stepanzubkov** [comment]
For me, on NixOS, qt6 theme works well. I think you are using sddm-greeter compiled with qt5. What is the output of command `sddm-greeter --version` for you?

**Comment by GaetanLepage** [comment]
Hmm, weird. I have not specified anything special regarding sddm. Here is [the relevant config](https://github.com/GaetanLepage/nix-config/blob/3c4b02afd6c24ebf445010d12e8144bb14783927/nixos/framework/wayland.nix#L18-L40).
```
❯ sddm-greeter --version
[00:28:19.395] (II) GREETER: High-DPI autoscaling Enabled
sddm-greeter 
```

**Comment by GaetanLepage** [comment]
> Hmm, weird. I have not specified anything special regarding sddm. Here is [the relevant config](https://github.com/GaetanLepage/nix-config/blob/3c4b02afd6c24ebf445010d12e8144bb14783927/nixos/framework/wayland.nix#L18-L40).

Am I doing anything wrong ? Are you on `nixos-unstable` as well ?

**Comment by stepanzubkov** [comment]
> > Hmm, weird. I have not specified anything special regarding sddm. Here is [the relevant config](https://github.com/GaetanLepage/nix-config/blob/3c4b02afd6c24ebf445010d12e8144bb14783927/nixos/framework/wayland.nix#L18-L40).
> 
> Am I doing anything wrong ? Are you on `nixos-unstable` as well ?

You should try qt5 theme
